config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#index"
  get "/spells", to: "spells#index"
  # creare a route that brings up the form
  get "/spells/new", to:"spells#new", as: "spell_new"
  # creare a route that brings up the form to edit
  get "/spells/:id/edit", to:"spells#edit", as: "spell_edit"
  post "/spells", to: "spells#create", as:"spells_create"
  get "/spells/:id", to: "spells#show", as:"spell"
  put "/spells/:id", to: "spells#update", as:"spell_update"
  delete "/spells/:id", to: "spells#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spell.rb
class Spell < ApplicationRecord
    validates :name, presence: true
    validates :category, presence: true
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index 
        
    end 
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
        skip_before_action :verify_authenticity_token
        
        # @@spells = [
        #     {id:1, name:"Fireball", description: "Ball of fire!", category: "fire"},
        #     {id:2, name: "Magic Missle", description: "A missle of magic", category: "force"},
        #     {id:3, name: "Avada Kedava", description: "It kills everyone except harry potter", category: "death"}   
        # ]

        before_action :set_spell, only: [:show, :update, :destroy, :edit]
        
        def index
            # render :index, locals: {spells: @@spells} 
            @spells = Spell.all
        end
        
        def show
            @spell = Spell.find(params[:id])
        end
        
        def new 
    
        end
        
        def edit 
            @spell = Spell.find(params[:id])
        end 
        
        def create
            @spell = Spell.create(spell_params)
            if @spell.save
                flash[:created] = "New Spell Created!"
                redirect_to spells_path
            else
                flash[:error] = @spell.errors.full_messages.to_sentence
                # render 'new'
                redirect_to spell_new_path
                # render :new
            end
        end
        
        def update
             @spell.update(spell_params)
             if @spell.save
                flash[:updated] = "New Spell Updated!"
                redirect_to spells_path
             else
                flash.now[:error] = @spell.errors.full_messages.to_sentence
            end
             
        end
        
        def destroy 
            @spell.destroy
            redirect_to spells_path
            
        end
    
        private 
    
        def set_spell
            @spell = Spell.find(params[:id])
        end

        def spell_params
            params.require(:spells).permit(:name, :category, :description)
        end
end  
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpellApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%=key%>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1> Welcome to the best site ever </h1>

app/views/shared/_navbar.html.erb
<nav class="navigation">
    <%=link_to "Create a new Spell", spell_new_path%>
</nav>

app/views/spells/edit.html.erb
<main id="pages-new">
    <h1> Update <%= @spell.name %> </h1>
    <form action="<%=spell_update_path(@spell.id)%>" method="POST">
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
    <input type="hidden" name="_method" value="put">
        <div class="field">
            <label>Name</label>
            <input type="text" name="spells[name]" value="<%= @spell.name %>" />
        </div>
        <div class="field">
        <label>Type</label>
        <input type="text" name="spells[category]" value="<%= @spell.category %>" />
        </div>
        <div class="field">
            <label>Description</label>
            <textarea name="spells[description]"  ><%= @spell.description %> </textarea>
        </div>
        <input type="submit" value="Update Spell">
    </form>
</main>

app/views/spells/index.html.erb
<main id="pages-index">

    <h1> All the spells </h1>
    <section class="card-deck">
    <%@spells.sort.each do |spell|%>
        <div class="card <%=spell[:category]%>">
            <h5><%=spell[:name]%></h5>
            <p><%=spell[:description]%></p>
            <%= link_to "See More", spell_path(spell[:id])%>
        </div>
        <%end%>
        
    </section>
    

</main>

app/views/spells/new.html.erb
<main id="pages-new">
    <h1> Create a New Spell </h1>
    <form action="<%=spells_create_path%>" method="POST">
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
        <div class="field">
            <label>Name</label>
            <input type="text" name="spells[name]" />
        </div>
        <div class="field">
        <label>Type</label>
        <input type="text" name="spells[category]" />
        </div>
        <div class="field">
            <label>Description</label>
            <textarea name="spells[description]"> </textarea>
        </div>
        <input type="submit" value="Create a Spell">
    </form>
</main>

app/views/spells/show.html.erb
<main id="pages-show">
    <h1 class="<%=@spell.category%>"><%=@spell.name%></h1>
    <section class="spell-content"> 
        <h2>Type: <%=@spell.category.capitalize%></h2>
        <p><%=@spell.description%> </p>
        <div class="button-container"> 
            <%= button_to "Delete Spell", {action: "destroy", id: @spell.id}, {method: :delete, class: "btn danger", data: {confirm: "Are you for real?"}}%>
            <%= button_to "Update Spell", {action: "edit", id: @spell.id}, {method: :get, class: "btn warning"}%>
        </div>
    </section>
</main>